import ast

ast.alias(name='ast_alias')
ast.AnnAssign(target=ast.Name(id='ast_AnnAssign_target'), annotation=ast.Name(id='ast_AnnAssign_annotation'), simple=0)
ast.arg(arg='ast_arg')
ast.Assert(test=ast.Name(id='ast_Assert_test'))
ast.Assign(value=ast.Name(id='ast_Assign_value'))
ast.AsyncFor(target=ast.Name(id='ast_AsyncFor_target'), iter=ast.Name(id='ast_AsyncFor_iter'))
ast.AsyncFunctionDef(name='ast_AsyncFunctionDef', args=ast.arguments())
ast.Attribute(value=ast.Name(id='ast_Attribute_value'), attr='ast_Attribute_attr')
ast.AugAssign(target=ast.Name(id='ast_AugAssign_target'), op=ast.Add(), value=ast.Name(id='ast_AugAssign_value'))
ast.Await(value=ast.Name(id='ast_Await_value'))
ast.BinOp(right=ast.Name(id='ast_BinOp_right'), left=ast.Name(id='ast_BinOp_left'), op=ast.BitAnd())
ast.BoolOp(op=ast.And())
ast.Call(func=ast.Name(id='ast_Call_func'))
ast.ClassDef(name='ast_ClassDef')
ast.Compare(left=ast.Name(id='ast_Compare_left'))
ast.comprehension(target=ast.Name(id='ast_comprehension_target'), is_async=0, iter=ast.Name(id='ast_comprehension_iter'))
ast.Constant(value='ast_Constant')
ast.DictComp(key=ast.Name(id='ast_DictComp_key'), value=ast.Name(id='ast_DictComp_value'))
ast.Expr(value=ast.Name(id='ast_Expr_value'))
ast.Expression(body=ast.Name(id='ast_Expression_body'))
ast.For(target=ast.Name(id='ast_For_target'), iter=ast.Name(id='ast_For_iter'))
ast.FormattedValue(value=ast.Name(id='ast_FormattedValue_value'), conversion=-1)
ast.FunctionDef(name='ast_FunctionDef', args=ast.arguments())
ast.FunctionType(returns=ast.Name(id='ast_FunctionType_returns'))
ast.GeneratorExp(elt=ast.Name(id='ast_GeneratorExp_elt'))
ast.If(test=ast.Name(id='ast_If_test'))
ast.IfExp(test=ast.Name(id='ast_IfExp_test'), body=ast.Name(id='ast_IfExp_body'), orelse=ast.Name(id='ast_IfExp_orelse'))
ast.keyword(value=ast.Name(id='ast_keyword_value'))
ast.Lambda(args=ast.arguments(), body=ast.Name(id='ast_Lambda_body'))
ast.ListComp(elt=ast.Name(id='ast_ListComp_elt'))
ast.match_case(pattern=ast.MatchAs())
ast.Match(subject=ast.Name(id='ast_Match_subject'))
ast.MatchClass(cls=ast.Name(id='ast_MatchClass_cls'))
ast.MatchSingleton(value=True)
ast.MatchValue(value=ast.Name(id='ast_MatchValue_value'))
ast.Name(id='ast_Name')
ast.NamedExpr(target=ast.Name(id='ast_NamedExpr_target'), value=ast.Name(id='ast_NamedExpr_value'))
ast.ParamSpec(name='ast_ParamSpec')
ast.SetComp(elt=ast.Name(id='ast_SetComp_elt'))
ast.Starred(value=ast.Name(id='ast_Starred_value'))
ast.Subscript(value=ast.Name(id='ast_Subscript_value'), slice=ast.Name(id='ast_Subscript_slice'))
ast.TypeAlias(name=ast.Name(id='ast_TypeAlias'), value=ast.Name(id='ast_TypeAlias_value'))
ast.TypeIgnore(lineno=0, tag='ast_TypeIgnore_tag')
ast.TypeVar(name='ast_TypeVar')
ast.TypeVarTuple(name='ast_TypeVarTuple')
ast.UnaryOp(op=ast.UAdd(), operand=ast.Name(id='ast_UnaryOp_operand'))
ast.While(test=ast.Name(id='ast_While_test'))
ast.withitem(context_expr=ast.Name(id='ast_withitem_context_expr'))
ast.YieldFrom(value=ast.Name(id='ast_YieldFrom_value'))
